### ISSUE TITLE
IMDB fetching is  completely down?

### ISSUE THREAD

**Issue by miziomenca** [andig/videodb#149] opened 2022-11-23 12:58 UTC
Hi,
fetching data from imdb seems to be totaly broken. I'm sorry, i have not  knowhow to bring help to the VideoDB Project. Sorry, i am a bartender, i can build just a perfect Negroni but my entire collection of dvd and any kind of support for films is on my VideoDB installation since about 15 years ago! Please... help.

**Comment by pbenke** [comment] 2022-11-25 19:58
It works again

**Comment by miziomenca** [comment] 2022-11-28 12:31
It's TRUE!!! Thank you so much. I was too worried.

**Comment by johanneskonst** [comment] 2022-11-28 16:33
Had the same issue, was able to do a lookup for a title but it failed fetching the details page for a movie.
Might be a referrer issue or some other partial limitation on imdb's end.
The error-message could be a bit more descriptive imo, might work on that...
Commenting here for my own reference as well...

**Comment by miziomenca** [comment] 2022-11-29 12:46
Again the same problem: 403 forbidden. Yesterday the fetching was almost right, didn't works rating and director but....
Today again comlpetely unworking.

**Comment by jbjoret** [comment] 2022-11-29 18:29
Mmm issue is there again as described. Search will find the IMDB URL but cannot fetch the page. Since the page loads in a browser but the same forbidden error is reproduceable with CURL, I suspect either a browser agent issue or a blocker to enforce ads sponsoring to be displayed (if this is the case, it will be difficult to work it around).

**Comment by pbenke** [comment] 2022-12-01 19:40
It is indeed issue with Guzzle PHP HTTP client default user agent. It can be temporary fixed by replacing line 103 of `core/httpclient.php` with something like this:

```php
$clientConfig = [
    'headers' => [
        'User-Agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.246',
    ],
];
$client = new GuzzleHttp\Client($clientConfig);
```

**Comment by copperhead57** [comment] 2022-12-02 04:22
building on @pbenke work above.
my branch 403-error-imdb applies above in a more permanent way.
requires changes to function.php, indb.php and trace.php.
I have only done very basic testing and have not received a 403 error.
any feedback welcome

**Comment by miziomenca** [comment] 2022-12-02 19:40
Hi @copperhead57 thank you for efforts and work. I've tried a brand new installation with your updated php. No more 403 forbidden error but in my case it doesn't works. When i try to find a new film the VideoDB doesn't find any title. I tryed to force the fetching by insert in "external Id" the code of a film in format "imdb:xxxxxxx". The result is the complete list of actors but without images and cover. OK for rating, country, year, plot and duration.
Sorry for my bad english.
![Immagine 2022-12-02 203940](https://user-images.githubusercontent.com/34900503/205373118-5b37c3b3-1c50-4f40-a218-856c4e28bf03.jpg)

**Comment by johanneskonst** [comment] 2022-12-02 19:49
might be that imdb has changed more then just a useragent check. there should be a test for this but i'm unsure if that still works as needed...Message ID: ***@***.***>

**Comment by copperhead57** [comment] 2022-12-02 20:46
hi @miziomenca , I did notice that images are not being returned I will be looking into over coming days, also simplifying the 403 code.
if you use my branch pre-master it includes most patches outstanding in andig project, which fixes using inmdb online

**Comment by copperhead57** [comment] 2022-12-04 11:26
hi @miziomenca, my branch pre-master now includes fixes for genre and actor images.
Again I have only done minor testing so any feedback welcome.
I have noticed that some actor images are only returned after editing the record.

**Comment by johanneskonst** [comment] 2022-12-05 09:50
Had a looksee. There's a big typo in httpClient that suprisingly nobody noticed in 5 (?) years.
The used Guzzle client is also pretty old, might be wise to update that one as well.

Anyway, instead of changing 16 files I would also opt for @pbenke 's approach and 'fix' this in httpClient function itself.
I'll open a PR shortly with some more details...

**Comment by copperhead57** [comment] 2022-12-05 11:57
hi @johanneskonst 
your solution much more elegant.
can i suggest using
HTTP_ACCEPT
HTTP_ACCEPT_LANGUAGE

**Comment by johanneskonst** [comment] 2022-12-05 12:30
@copperhead57 I've thought about using HTTP_ACCEPT but then the user's browser would dictate what VideoDB would be able to accept, so if my browser prefers gzipped JSON and the engine used would be able to deliver that it would then serve something that VideoDB does not know how to handle, hence the constant _text/html_ bit (since it does know how to parse that)

**Comment by miziomenca** [comment] 2022-12-05 12:49
Hello! I've just made another new installation from zero of "149-fix-from-johanneskonst" branch by @copperhead57 but nothing seems to be changed. No cover and actors images. But...now the search of title works.

**Comment by johanneskonst** [comment] 2022-12-05 12:54
Cover and actor probably has another root-cause, I'll take a look...

**Comment by copperhead57** [comment] 2022-12-05 12:55
@miziomenca i haven't yet put the fix for images and genre in that branch yet it only has 403 fix.

**Comment by johanneskonst** [comment] 2022-12-06 17:08
actor and cover images is broken, i'm working on that now... ---- On Tue, 06 Dec 2022 18:05:37 +0100  ***@***.***  wrote ----
I'm sorry @copperhead57 for trouble,  i tryed new installation with  "pre-master" and "149-fix-genre-actorimage" branch but actors images and cover fetching dosen't works. Just for me?

**Comment by copperhead57** [comment] 2022-12-06 23:16
@miziomenca have you tried pre-master with adding a new movie..
with already added records i think the value in field 'Actor thumbnail retry' on configuration page  is stopping the refresh of some of missing images, i a going to look into this to see if this is the case

@johanneskonst - i think temporarily changing value to 0 may get over above but havent got time today to test

**Comment by copperhead57** [comment] 2022-12-07 03:23
@miziomenca  - I have been able to update my branch '149-fix-genre-actorimage' with the fixes for genre and actor images which also includes @johanneskonst 403 fix.
i have tested setting field 'Actor thumbnail retry' on configuration page to say 5 (5 seconds) temporarily for existing records then when viewing the record the images do seem to be returned. 

WARNING if the field is NOT reset to its original or higher or default value very time a record is viewed all actor images will be retrieved from the web rather than the image saved to computer.

**Comment by miziomenca** [comment] 2022-12-07 19:29
Hi @copperhead57. Another one new installation with your "149-fix-genre-actorimage" branch on an empty database and 'Actor thumbnail retry' sets to 5. The rsesult is the same, some actor images are with the icon of broken image and  others are with "?".
Same with "pre-master" branch.
SQL server version: 5.7.35-38-log - Percona Server (GPL), Release 38, Revision 3692a61
UTF8_general_ci

**Comment by miziomenca** [comment] 2022-12-07 19:29
![Screenshot_20221207_202105](https://user-images.githubusercontent.com/34900503/206277431-4d9f3095-e15a-46f7-bbba-24ddd09cc0c3.png)

**Comment by jbjoret** [comment] 2022-12-08 06:05
> ![Screenshot_20221207_202105](https://user-images.githubusercontent.com/34900503/206277431-4d9f3095-e15a-46f7-bbba-24ddd09cc0c3.png)
> 
> 

This looks very much like a cache issue: the links to the pictures in your database relate to a local cache, if the pictures are deleted in the cache (local files), but you don't tell videodb to delete/refresh the cache this is what you would see.

**Comment by johanneskonst** [comment] 2022-12-08 11:08
Yes, this does seem like a cache issue / file permission issue.
@miziomenca if you try to view one of the images directly what kind of error do you get?
eg. right click on one of the missing images, select "view this image" or "copy image address" and then request that with browser.
it should look like your-videodb-url/cache/img/2/20f7ca319c2ff97114e4f3f2ee1fad5e.jpg
Since you mentioned new installation it might be that the cache folder does not have write permissions, setting those might fix this properly...
Closing this for now since the initial issue is fixed. If you still have problems please open a new issue.

Thank you all!

**Closed by johanneskonst** 2022-12-08 11:08 UTC

**Comment by miziomenca** [comment] 2022-12-08 15:46
Hello all of you! In these days i tryed new installations from @copperhead57 branches on new sql databases. Cache folder is empty as the database. Just one film for testing.

**Comment by copperhead57** [comment] 2022-12-12 05:27
@miziomenca please try andig branch 'master'. if the problem still occurs please open a new issue.
