### ISSUE TITLE
No pictures / No IMDB Cast V4.0.0

### ISSUE THREAD

**Issue by kevvie81** [andig/videodb#73] opened 2014-12-11 09:21 UTC
I have 2 problems atm, the first is IMDB casts doesn't pull through. The second is no picture is showing, ie No covers and no pictures also showing when I go to the IMDB tab, however when I click open in browser it does show (it then goes to the actual website in a new window).

**Comment by nobicycle** [comment] 2016-07-20 04:21
I confirm this is an issue and confirm the solution works. I wonder what is the root cause and permanent solution?
Best wishes and many thanks Videodb

## System
$uname -a && php56 -v && mysql -V
Linux localhost.localdomain 4.6.2-1-MANJARO #1 SMP PREEMPT Wed Jun 8 11:00:08 UTC 2016 x86_64 GNU/Linux
PHP 5.6.21 (cli) (built: May 24 2016 19:59:20) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
mysql  Ver 15.1 Distrib 10.1.14-MariaDB, for Linux (x86_64) using readline 5.1

**Comment by kec2** [comment] 2016-10-23 11:41
I believe that this issue has been fixed.

**Comment by ibrouwer** [comment] 2019-01-30 21:09
No, the issue has not been fixed with me. I tried all the things mentioned below, but no pictures actually show up. Any other suggestions ?

**Comment by kec2** [comment] 2019-01-30 21:41
I will have a look at it this weekend.

Regards Klaus

On January 30, 2019 9:09:04 PM UTC, ibrouwer <notifications@github.com> wrote:

No, the issue has not been fixed with me. I tried all the things mentioned below, but no pictures actually show up. Any other suggestions ?

**Comment by kec2** [comment] 2019-02-08 19:03
Hey ibrouwer

Did you try the latest pull request?

Be Klaus

On January 30, 2019 9:09:04 PM UTC, ibrouwer <notifications@github.com> wrote:

No, the issue has not been fixed with me. I tried all the things mentioned below, but no pictures actually show up. Any other suggestions ?

**Comment by johanneskonst** [comment] 2022-12-22 15:15
Did some testing, looks like the normal workflow of adding/updating a movie and showing posters/actor thumbnails works.
We probably need some way to test when supplier-side changes break things, but that's another issue...
Closing as resolved, thanks!

**Closed by johanneskonst** 2022-12-22 15:15 UTC
Labels: bug
